AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-first-sam

  Sample SAM Template for my-first-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      # checkov:skip=CKV_AWS_116:Synchronous invocation only:API Gateway is the only client of this function
      # checkov:skip=CKV_AWS_117:AWS Lambda Function is not assigned to access within VPC
      # checkov:skip=CKV_AWS_115:AWS Lambda Function Reserved Concurrent Executions not necessary 

      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  # checkov:skip=CKV_AWS_18: "Ensure the S3 bucket has access logging enabled"
  # checkov:skip=CKV_AWS_21: "Ensure the S3 bucket has versioning enabled"
 
  VulnIntelBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      #BucketName: deployments usually don't explicitly set bucket names to avoid conflicts
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

    # checkov:skip=CKV_AWS_117: "Ensure that AWS Lambda function is configured inside a VPC"
    # checkov:skip=CKV_AWS_115: "Ensure that AWS Lambda function is configured for function-level concurrent execution limit"
    # checkov:skip=ckv_aws_116: "Ensure the Lambda function is configured for dlq"
  
  NVDFetch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ingest/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 120
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: sw-us-east-1-vuln-intel
          NVD_API_KEY: !Sub '{{resolve:secretsmanager:nvd-api-key:SecretString:NVD_API_KEY}}'
      Policies:
        - S3WritePolicy:
            BucketName: sw-us-east-1-vuln-intel
      Events:
        NVDFetch:
          Type: Api
          Properties:
            Path: /ingest
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
